apiVersion: static-route.ibm.com/v1
kind: StaticRoute
metadata:
  name: example-static-route-with-selector
spec:
  subnet: "192.168.1.0/24"
  selectors:
    - 
      key: "kubernetes.io/arch"
      operator: In
      values: 
        - "amd64"
