apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: static-route-operator
spec:
  selector:
    matchLabels:
      name: static-route-operator
  template:
    metadata:
      labels:
        name: static-route-operator
    spec:
      serviceAccountName: static-route-operator 
      hostNetwork: true
      tolerations:
      - operator: Exists
      containers:
      - name: static-route-operator
        image: REPLACE_IMAGE
        imagePullPolicy: Always
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: OPERATOR_NAME
          value: "static-route-operator"
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
